web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'https://mi-git.univ-tlse2.fr'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://mi-git.univ-tlse2.fr/mamadou.mendy/code-kinder-project'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
